In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from dotenv import load_dotenv

In [50]:
load_dotenv()

True

In [2]:

# Sample documents
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [3]:
query="keyword-based search"

In [4]:
import re
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    return text

In [5]:
preprocess_documents=[preprocess_text(doc) for doc in documents]

In [6]:
preprocess_documents

['this is a list which containig sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [7]:
print("Preprocessed Documents:")
for doc in preprocess_documents:
    print(doc)

Preprocessed Documents:
this is a list which containig sample documents
keywords are important for keywordbased search
document analysis involves extracting keywords
keywordbased search relies on sparse embeddings


In [8]:
print("Preprocessed Query:")
print(query)

Preprocessed Query:
keyword-based search


In [9]:
preprocessed_query = preprocess_text(query)

In [10]:
preprocessed_query

'keywordbased search'

In [11]:
vector=TfidfVectorizer()
X=vector.fit_transform(preprocess_documents)

In [13]:
X.toarray()

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [14]:
X.toarray()[0]

array([0.        , 0.        , 0.37796447, 0.        , 0.37796447,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
       0.        , 0.37796447, 0.        , 0.        , 0.37796447,
       0.37796447])

In [15]:
query_embedding=vector.transform([preprocessed_query])

In [16]:
query_embedding.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ]])

In [17]:
similarities = cosine_similarity(X, query_embedding)

In [18]:
similarities

array([[0.        ],
       [0.50551777],
       [0.        ],
       [0.48693426]])

##### The np.argsort function in Python's NumPy library returns the indices that would sort an array in ascending order. Unlike np.sort(), which returns a sorted copy of the data, argsort performs an "indirect sort" by providing a roadmap of index positions.

In [19]:
np.argsort(similarities,axis=0)

array([[0],
       [2],
       [3],
       [1]])

In [20]:
ranked_indices = np.argsort(similarities, axis=0)[::-1].flatten()

In [21]:
ranked_indices

array([1, 3, 2, 0])

In [22]:
# Output the ranked documents
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: Document {idx+1}")

Rank 1: Document 2
Rank 2: Document 4
Rank 3: Document 3
Rank 4: Document 1


In [26]:
doc_path="Enrolment_Guide_2021_E.pdf"

In [24]:
from langchain_community.document_loaders import PyPDFLoader

In [27]:
loader=PyPDFLoader(doc_path)

In [28]:
docs=loader.load()

In [34]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [35]:
splitter = RecursiveCharacterTextSplitter(chunk_size=200,chunk_overlap=30)

In [36]:
chunks = splitter.split_documents(docs)

In [38]:
chunks[:5]

[Document(metadata={'producer': 'Adobe PDF Library 15.0', 'creator': 'Adobe InDesign 16.1 (Macintosh)', 'creationdate': '2021-04-12T20:47:55-04:00', 'moddate': '2021-04-20T08:59:35-04:00', 'title': 'Benefits Summary and Enrolment Guide', 'trapped': '/False', 'source': 'Enrolment_Guide_2021_E.pdf', 'total_pages': 16, 'page': 0, 'page_label': '1'}, page_content='Benefits Summary and Enrolment Guide\nLife’s brighter under the sun\nTOTAL BENEFITS & \nSAVINGS @ WORK\nTM'),
 Document(metadata={'producer': 'Adobe PDF Library 15.0', 'creator': 'Adobe InDesign 16.1 (Macintosh)', 'creationdate': '2021-04-12T20:47:55-04:00', 'moddate': '2021-04-20T08:59:35-04:00', 'title': 'Benefits Summary and Enrolment Guide', 'trapped': '/False', 'source': 'Enrolment_Guide_2021_E.pdf', 'total_pages': 16, 'page': 1, 'page_label': '2'}, page_content='Contents\nChoice is key with the LifeLabs Benefits Plan!  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  1'),
 Document(metadat

In [51]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(
    #api_key=os.environ[OPENAI_API_KEY],
    model="text-embedding-3-small"   # or "text-embedding-3-large"
)

In [46]:
#!pip install -qU "langchain-chroma>=0.1.2"

In [ ]:
from langchain_chroma import Chroma

vectorstore=Chroma.from_documents(chunks,embeddings)

vectorstore_retreiver = vectorstore.as_retriever(search_kwargs={"k": 3})

In [53]:
vectorstore_retreiver

VectorStoreRetriever(tags=['Chroma', 'OpenAIEmbeddings'], vectorstore=<langchain_chroma.vectorstores.Chroma object at 0x0000021CB4451310>, search_kwargs={'k': 3})

In [55]:
#!pip install rank_bm25

In [ ]:
from langchain_community.retrievers import BM25Retriever

keyword_retriever = BM25Retriever.from_documents(chunks)

In [66]:
keyword_retriever.k =  3

In [74]:
#!pip install langchain-classic

In [76]:
from langchain_classic.retrievers import EnsembleRetriever

In [77]:
ensemble_retriever = EnsembleRetriever(retrievers=[vectorstore_retreiver,keyword_retriever],weights=[0.3, 0.7])

In [78]:
# import sys
# import langchain
# print(langchain.__version__)
# print(langchain.__file__)

#### Mixing vector search and keyword search for Hybrid search
#### hybrid_score = (1 — alpha) * sparse_score + alpha * dense_score

In [80]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="gpt-4o-mini",   # fast + cheap
    temperature=0
)

In [82]:
from langchain_classic.chains import RetrievalQA

In [83]:
normal_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=vectorstore_retreiver
)

In [84]:
hybrid_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=ensemble_retriever
)

In [88]:
response1 = normal_chain.invoke("Extended Health Care & Dental coverage")

In [89]:
response1

{'query': 'Extended Health Care & Dental coverage',
 'result': 'Extended Health Care and Dental coverage typically refers to additional health benefits that go beyond standard health insurance. This can include services such as prescription drugs, vision care, paramedical services, and dental care. If you have specific questions about the coverage options or details, please let me know!'}

In [90]:
print(response1.get("result"))

Extended Health Care and Dental coverage typically refers to additional health benefits that go beyond standard health insurance. This can include services such as prescription drugs, vision care, paramedical services, and dental care. If you have specific questions about the coverage options or details, please let me know!
